version: "3.3"

services:
    fvtt:
        build:
            context: ./
            dockerfile: Dockerfile
            args:
                - NODEJS_VERSION=${NODEJS_VERSION:-18.15.0-r0}
                - FOUNDRY_DIR=${FOUNDRY_DIR:-.}
                - FOUNDRY_VERSION=${FOUNDRY_VERSION:-10.291}
        volumes:
            - ${ROOT_DIR:-foundry_data}/data:/home/foundry/fvttdata
        ports:
            - "127.0.0.1:30000:30000"
        deploy:
            resources:
                limits:
                    cpus: 0.50
                    memory: 512M
